/// Flutter icons AVIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AVIcons
///      fonts:
///       - asset: fonts/AVIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AVIcons {
  AVIcons._();

  static const _kFontFam = 'AVIcons';
  static const String? _kFontPkg = null;

  static const IconData fourStar = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
